<a href="https://colab.research.google.com/github/nihel-sliti/formationPython/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Creating NumPy Arrays**

In [1]:
import numpy as np

Now, let’s define a new array.

One-dimensional array:

In [2]:
amal=np.array([1,2,3])
amal

array([1, 2, 3])

Multidimensional array:

In [3]:
amal=np.array([[1,2,3],[22,4,6]])
amal

array([[ 1,  2,  3],
       [22,  4,  6]])

# **Array Shape/Reshape**

** Shape**

The shape of an array is the number of elements in each dimension.

To get the current shape of an array, we use the shape() function, it returns a tuple with each index having the number of corresponding elements.

In [4]:
amal.shape

(2, 3)

**Array Reshape**

Note that b is now a two-dimensiona array with 4 rows and 2 columns.


In [5]:
a=np.array([0,0,0,0,1,0,0,0])

In [6]:
b = a.reshape(4,2)
b

array([[0, 0],
       [0, 0],
       [1, 0],
       [0, 0]])

# **Array Indexing in NumPy**

Remember that arrays in Python always start with 0.

In [7]:
print(b[2,0])

1


# **Array Slicing in NumPy**

**Row selection**

In [8]:
print(b[2,:])

[1 0]


 **Column selection**

In [9]:
print(b[:, 1])

[0 0 0 0]


# **NumPy Random**

In [10]:
import numpy as np
value=np.random.random()
print(value)

0.486779101430572


We can also create arrays that contain random values between 0 and 1 by specifying the shape of the array:

In [11]:
array=np.random.random((2,5))
print(array)

[[0.63133291 0.37152393 0.09286076 0.02387162 0.54581812]
 [0.19652612 0.98110955 0.44184167 0.45855322 0.50325041]]


**Randint**

With the random.randint() function we create an array that contains random integers between a minimum value and a maximum value with a specified shape:

In [12]:
array=np.random.randint(2, 10)
print(array)

6


In [13]:
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[9 2 4 3]
 [3 8 2 6]]


# **Zeros and Full function**


The zeros function returns a new array of a given shape and type filled with zeros:

In [14]:
array=np.zeros(5)
print(array)


[0. 0. 0. 0. 0.]


In [15]:
array=np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [16]:
array=np.full(5, 1)
print(array)

[1 1 1 1 1]


The eye function returns a 2D array with ones on the diagonal and zeros elsewhere :

In [17]:
array=np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# **NumPy Addition**

In [18]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [19]:
A=np.add(x, y)
A

array([[ 6.,  8.],
       [10., 12.]])

In [20]:
A=x+y
A

array([[ 6.,  8.],
       [10., 12.]])

# **NumPy Subtraction**

In [21]:
Z=np.subtract(x, y)
Z

array([[-4., -4.],
       [-4., -4.]])

In [22]:
Z=x-y
Z

array([[-4., -4.],
       [-4., -4.]])